import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import "./globals.css";
import Header from "./components/header";


export const metadata: Metadata = {
  title: "Vivaan Verma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`antialiased`}
      >
        <div className="flex flex-col items-center justify-items-center min-h-screen bg-gradient-to-br from-slate-200 via-gray-50 to-slate-200 dark:from-slate-800 dark:via-black dark:to-slate-900">
          <Header></Header>
          {children}
        </div>
        <Analytics/>
      </body>
    </html>
  );
}
