import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";

const SprayLetters = localFont({
  src: "./fonts/SprayLetters.otf",
  variable: "--font-spray-letters",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SprayLetters.variable} antialiased`}
      >
        <div className="grid grid-rows-[10vh_90vh] items-center justify-items-center min-h-screen">
          <Header></Header>
          {children}
        </div>
        <Analytics/>
      </body>
    </html>
  );
}
